from pathlib import Path
from lxml import html,etree
BASE=Path(__file__).resolve().parents[1]
refs={1:'<p class="fuentes-oficiales"><strong>Fuentes de los fundamentos:</strong> <a href="https://agilemanifesto.org/iso/es/manifesto.html">Manifiesto por el Desarrollo Ágil de Software</a> y <a href="https://agilemanifesto.org/iso/es/principles.html">sus doce principios</a>. Los ejemplos del módulo explican su aplicación; no son resultados atribuidos a los firmantes. Consulta: 15 de septiembre de 2026.</p>',2:'<p class="fuentes-oficiales"><strong>Fuente normativa de Scrum:</strong> <a href="https://scrumguides.org/scrum-guide.html">The Scrum Guide, edición 2020</a>, de Ken Schwaber y Jeff Sutherland. Sus reglas se distinguen aquí de ejemplos y prácticas opcionales. Consulta: 15 de septiembre de 2026.</p>',3:'<p class="fuentes-oficiales"><strong>Fuente normativa:</strong> <a href="https://scrumguides.org/scrum-guide.html">The Scrum Guide, edición 2020</a>, para Product Goal, Product Backlog, refinamiento y Definition of Done. Historias, INVEST, DoR, MVP y técnicas de priorización se presentan como prácticas complementarias, no como requisitos de Scrum. Consulta: 15 de septiembre de 2026.</p>',4:'<p class="fuentes-oficiales"><strong>Fuente normativa:</strong> <a href="https://scrumguides.org/scrum-guide.html">The Scrum Guide, edición 2020</a>, para planificación, selección de trabajo y Sprint Goal. Las técnicas de estimación y los gráficos de seguimiento son complementarios y no obligatorios. Los ejemplos numéricos son didácticos. Consulta: 15 de septiembre de 2026.</p>',5:'<p class="fuentes-oficiales"><strong>Fuente normativa:</strong> <a href="https://scrumguides.org/scrum-guide.html">The Scrum Guide, edición 2020</a>, para autogestión, responsabilidades, Review y Retrospective. Los casos reales tienen sus fuentes junto al análisis, y los escenarios simulados se identifican expresamente. Consulta: 15 de septiembre de 2026.</p>'}
for n,s in refs.items():
    p=BASE/'entregables'/f'MODULO {n}'/'Contenido/contenido.html'; t=html.parse(str(p)); a=t.xpath('//article')[0]
    if not a.xpath('.//p[@class="fuentes-oficiales"]'):
        e=next(e for e in a if e.tag=='h2' and 'Recursos audiovisuales' in e.text_content())
        e.addprevious(html.fragment_fromstring(s))
    p.write_bytes(etree.tostring(t,method='html',encoding='utf-8',doctype='<!doctype html>'))
print('Fuentes oficiales agregadas junto a los recursos complementarios.')
