"""Revisión pedagógica autorizada de los módulos 2 a 5. Ejecución única."""
from pathlib import Path
from lxml import html, etree
from PIL import Image
import shutil, json, re

BASE=Path(__file__).resolve().parents[1]
QA=BASE/'.qa/revision-pedagogica-ia/antes'
QA.mkdir(parents=True,exist_ok=True)

def fr(s): return html.fragments_fromstring(s)
def sec(article,n):
    h=article.xpath(f'./h2[@id="seccion-{n}"]')[0]; out=[]
    for e in list(article)[list(article).index(h)+1:]:
        if e.tag=='h2': break
        out.append(e)
    return h,out
def replace(article,n,s,figures=True):
    h,old=sec(article,n); ix=list(article).index(h)+1
    keep=[e for e in old if e.tag=='figure'] if figures else []
    for e in old: article.remove(e)
    for e in fr(s)+keep: article.insert(ix,e); ix+=1
def append(article,n,s):
    h,old=sec(article,n); ix=list(article).index(old[-1])+1 if old else list(article).index(h)+1
    for e in fr(s): article.insert(ix,e); ix+=1
def repl_text(article,needle,text):
    cand=[e for e in article.xpath('.//p|.//li') if needle in ' '.join(e.text_content().split())]
    if len(cand)!=1: raise ValueError((needle,len(cand)))
    cand[0].getparent().replace(cand[0],fr(text)[0])
def opening(article,s):
    for e in list(article):
        if e.tag=='h2': break
        article.remove(e)
    for i,e in enumerate(fr(s)): article.insert(i,e)

for n in range(2,6):
    folder=BASE/'entregables'/f'MODULO {n}'/'Contenido'; out=QA/f'MODULO {n}'; out.mkdir(parents=True,exist_ok=True)
    for name in ('contenido.html','Contenido.docx'):
        shutil.copy2(folder/name,out/name)

# MÓDULO 2: enseñar el marco antes de comparar sus piezas.
p=BASE/'entregables/MODULO 2/Contenido/contenido.html'; tree=html.parse(str(p)); a=tree.xpath('//article')[0]
if a.get('data-revision-ia'): raise SystemExit('Módulo 2 ya revisado')
opening(a,'''<p>El equipo del asistente universitario con IA ya sabe por qué necesita aprender en ciclos cortos. Ahora debe decidir <em>cómo</em> organizar ese aprendizaje: quién ordena las necesidades, cómo se convierte una idea en un resultado verificable y cuándo se modifica el plan.</p>
<p>En este módulo vamos a recorrer primero <strong>Scrum</strong> como un sistema completo. Recién después estudiaremos <strong>Kanban, XP y Lean</strong>. Así, cada nombre aparecerá después de comprender el problema que resuelve.</p>
<h3>Cómo recorrer este módulo</h3><ol><li>Ver el ciclo general de Scrum sin memorizar vocabulario.</li><li>Comprender sus fundamentos, responsabilidades, artefactos y eventos.</li><li>Aplicarlo al asistente universitario.</li><li>Estudiar Kanban, XP y Lean con sus propios propósitos.</li><li>Elegir o combinar prácticas con una justificación.</li></ol>''')
replace(a,1,'''<p>No existe una única “metodología ágil” que sirva para cualquier situación. Los enfoques de este módulo ponen el foco en preguntas diferentes.</p>
<table><caption>Mapa inicial: qué pregunta ayuda a responder cada enfoque</caption><thead><tr><th>Enfoque</th><th>Pregunta central</th><th>Se desarrolla en</th></tr></thead><tbody>
<tr><td>Scrum</td><td>¿Cómo aprender y producir valor mediante ciclos breves con objetivos?</td><td>Secciones 2 a 6</td></tr><tr><td>Kanban</td><td>¿Cómo hacer visible y mejorar el flujo continuo de trabajo?</td><td>Secciones 7 y 8</td></tr><tr><td>XP</td><td>¿Qué prácticas técnicas ayudan a cambiar software sin perder calidad?</td><td>Sección 9</td></tr><tr><td>Lean</td><td>¿Cómo aumentar valor y reducir esperas, errores y trabajo innecesario?</td><td>Sección 10</td></tr></tbody></table>
<div class="analogia"><p><strong>Analogía de un hospital.</strong> La guardia, una cirugía programada y la mejora de un tratamiento pertenecen al mismo sistema, pero no se organizan igual. En proyectos ocurre lo mismo: la naturaleza de la demanda y el tipo de incertidumbre orientan la elección.</p></div>
<p>No comparamos todavía roles ni reuniones. Primero vamos a comprender cada enfoque desde adentro.</p>''')
replace(a,2,'''<p><strong>Scrum</strong> es un marco liviano para generar valor mediante soluciones adaptativas a problemas complejos. No describe cada técnica de trabajo: establece una estructura mínima para convertir ideas en resultados, inspeccionarlos y decidir el siguiente paso.</p>
<h3>2.1 El ciclo en lenguaje cotidiano</h3><ol><li>Ordenar las necesidades conocidas del producto.</li><li>Elegir un objetivo breve y trabajo posible para acercarse a él.</li><li>Construir un resultado utilizable durante un período de un mes o menos.</li><li>Inspeccionar el resultado con personas interesadas.</li><li>Mejorar tanto el producto como la forma de trabajar y repetir el ciclo.</li></ol>
<div class="analogia"><p><strong>Analogía del GPS.</strong> El destino orienta; la ruta actual es un plan. Cada tramo recorrido aporta información real sobre tránsito y desvíos. Recalcular no significa conducir sin rumbo: significa conservar el destino y adaptar el camino con evidencia.</p></div>
<p>En el asistente universitario, un primer ciclo podría buscar que el sistema responda consultas de inscripción usando un conjunto aprobado de documentos. El resultado deberá ser verificable por estudiantes y por la oficina de alumnos; “investigar modelos” por sí solo no demuestra que exista una capacidad utilizable.</p>''')
replace(a,3,'''<p>Scrum se apoya en el <strong>empirismo</strong>: aprender de la experiencia y decidir con lo observado. Lean aporta foco en lo esencial y reducción del desperdicio.</p>
<h3>3.1 Los tres pilares</h3><ul><li><strong>Transparencia:</strong> el trabajo y sus criterios deben ser visibles y entendibles. Si “respuesta correcta” significa algo distinto para cada persona, la inspección engaña.</li><li><strong>Inspección:</strong> se observa el producto y el progreso con frecuencia suficiente para detectar problemas. Inspeccionar no es vigilar personas.</li><li><strong>Adaptación:</strong> cuando la evidencia contradice el plan, se ajusta el producto o la forma de trabajar. Observar sin actuar no produce aprendizaje.</li></ul>
<p>Para el asistente, transparencia implica conocer qué documentos usa y qué pruebas debe superar. Inspección significa revisar respuestas con una muestra preparada y con usuarios. Adaptación puede llevar a corregir fuentes, reformular una función o reducir el alcance del ciclo.</p>
<h3>3.2 Los cinco valores</h3><p><strong>Compromiso, foco, apertura, respeto y coraje</strong> orientan las decisiones. Coraje puede significar mostrar que una respuesta convincente es incorrecta; apertura, comunicar el hallazgo; respeto, discutir la evidencia sin atacar a quien propuso la solución.</p>
<div class="criterio-profesional"><p><strong>Criterio profesional.</strong> Una reunión solo aporta valor si mejora transparencia, inspección o adaptación.</p></div>''')
replace(a,4,'''<p>Scrum define tres <strong>responsabilidades</strong> dentro de un único Scrum Team. No son niveles jerárquicos ni cargos presentes en Kanban por obligación.</p>
<h3>4.1 Product Owner: orientar valor</h3><p>El <strong>Product Owner</strong> responde por maximizar el valor y por gestionar eficazmente el Product Backlog: explicita el Product Goal, comunica y ordena sus elementos y asegura que la lista sea visible y entendida. Puede delegar tareas de redacción, pero conserva la responsabilidad.</p>
<p>En el caso conductor, conversa con estudiantes, oficina de alumnos, seguridad y equipo técnico para decidir qué necesidad atender primero. No asigna cómo programar ni promete resultados que el equipo no evaluó.</p>
<h3>4.2 Developers: crear un incremento utilizable</h3><p>Los <strong>Developers</strong> son quienes crean cualquier aspecto del incremento. En IA pueden incluir perfiles de datos, software, experiencia de usuario, evaluación y operaciones. Juntos elaboran el plan del Sprint, incorporan calidad, adaptan el plan y se responsabilizan profesionalmente.</p>
<p>El término no significa solamente “programadores”. El conjunto debe poseer o adquirir las capacidades necesarias; aun así puede coordinar dependencias externas de manera visible.</p>
<h3>4.3 Scrum Master: ayudar a que Scrum funcione</h3><p>El <strong>Scrum Master</strong> responde por establecer Scrum y mejorar la efectividad del equipo. Enseña, facilita, ayuda a remover impedimentos y trabaja con la organización. No distribuye tareas ni recibe el Daily como reporte.</p>
<table><caption>Una decisión, tres responsabilidades</caption><thead><tr><th>Situación</th><th>Aporte principal</th></tr></thead><tbody><tr><td>Las respuestas sobre becas son menos confiables que las de inscripción.</td><td>El Product Owner revisa prioridad y valor con interesados.</td></tr><tr><td>Hay que mejorar datos, interfaz y pruebas.</td><td>Developers adaptan el plan técnico y mantienen la calidad.</td></tr><tr><td>La validación queda bloqueada por aprobaciones tardías.</td><td>El Scrum Master ayuda al equipo y a la organización a mejorar ese sistema.</td></tr></tbody></table>''')
replace(a,6,'''<p>Los eventos de Scrum crean una <strong>cadencia</strong> para inspeccionar y adaptar. Todos ocurren dentro del Sprint; no son ceremonias para controlar ocupación.</p>
<h3>6.1 Sprint</h3><p>Es el período de un mes o menos en el que se crea valor. Su duración permanece estable para aportar ritmo. Durante él no se hacen cambios que pongan en riesgo el Sprint Goal ni se reduce calidad; el alcance puede aclararse y renegociarse al aprender.</p>
<h3>6.2 Sprint Planning</h3><p>El Scrum Team acuerda por qué el Sprint es valioso, qué puede hacerse y cómo se realizará. El resultado inicial es el Sprint Backlog. Seleccionar elementos es un <strong>pronóstico</strong>; el compromiso es el Sprint Goal.</p>
<h3>6.3 Daily Scrum</h3><p>Durante quince minutos, los Developers inspeccionan el progreso hacia el Sprint Goal y adaptan su plan. Pueden usar las preguntas que les resulten útiles. No es un reporte al Scrum Master ni reemplaza conversar cuando aparece un bloqueo.</p>
<h3>6.4 Sprint Review</h3><p>Scrum Team e interesados inspeccionan el resultado y conversan sobre cambios del contexto. Es una sesión de trabajo, no solo una demostración ni una aprobación para liberar.</p>
<h3>6.5 Sprint Retrospective</h3><p>El Scrum Team analiza cómo aumentar calidad y efectividad y decide mejoras. Para un Sprint de un mes tiene un máximo de tres horas; en Sprints más cortos suele durar menos.</p>
<h3>6.6 Caso completo: un Sprint del asistente universitario</h3><ol><li><strong>Objetivo:</strong> responder consultas frecuentes de inscripción con información aprobada y mostrar la fuente utilizada.</li><li><strong>Plan:</strong> preparar veinte consultas representativas, conectar los documentos vigentes, construir la interacción y registrar respuestas incorrectas.</li><li><strong>Inspección diaria:</strong> el equipo detecta que varios documentos usan nombres distintos para el mismo trámite y ajusta el plan.</li><li><strong>Incremento:</strong> una versión utilizable cumple la Definition of Done y supera el umbral acordado en la muestra. El umbral es didáctico y no garantiza desempeño futuro.</li><li><strong>Review:</strong> estudiantes y personal prueban el resultado; aparece la necesidad de indicar cuándo la información puede estar desactualizada.</li><li><strong>Retrospectiva:</strong> el equipo decide involucrar antes a la persona que valida documentos.</li></ol>
<div class="criterio-profesional"><p><strong>Criterio profesional.</strong> En IA, un experimento puede enseñar que una alternativa no funciona. Para llamarlo incremento de Scrum, el resultado debe ser utilizable y cumplir la Definition of Done.</p></div>''')
replace(a,7,'''<p><strong>Kanban</strong> es una estrategia para optimizar el flujo de valor mediante un sistema de trabajo visible. Puede aplicarse sobre un proceso existente y no exige Product Owner, Scrum Master, Sprints ni una reunión particular.</p>
<h3>7.1 De la señal industrial al trabajo del conocimiento</h3><p>El término proviene de señales visuales utilizadas en sistemas productivos japoneses. En trabajo del conocimiento, las tarjetas hacen visible una demanda que no se puede observar físicamente. La inspiración histórica no vuelve idénticos a una fábrica y a un equipo de software.</p>
<h3>7.2 Qué debe mostrar un tablero</h3><p>Un tablero representa estados reales y políticas. Para el asistente podríamos usar “Opciones”, “Preparado”, “En construcción”, “En validación” y “Terminado”. Una tarjeta bloqueada permanece visible; moverla a una columna de espera no elimina el trabajo iniciado.</p>
<p>El sistema necesita una definición clara de cuándo una tarjeta entra y sale de cada estado. Las columnas por sí solas no constituyen Kanban.</p>
<div class="analogia"><p><strong>Analogía de una autopista.</strong> Agregar autos a un embotellamiento no aumenta la velocidad de llegada. Limitar el ingreso permite terminar lo iniciado y revela dónde se forma la cola.</p></div>''')
append(a,9,'''<h3>9.6 XP e inteligencia artificial</h3><p>Las prácticas técnicas también ayudan en productos con IA, pero debemos distinguir tipos de prueba. Un test automatizado puede verificar que una API respete permisos y formatos; un conjunto de evaluación examina la calidad de respuestas sobre casos conocidos. Ninguno demuestra por sí solo ausencia de errores en todas las consultas futuras.</p><p>Un asistente generativo puede proponer tests o revisar código, pero el equipo conserva el criterio, verifica los resultados y protege datos sensibles. Eso no reemplaza el aprendizaje compartido de la programación en pareja.</p>''')
a.set('data-revision-ia','2026-09-16'); p.write_bytes(etree.tostring(tree,encoding='utf-8',method='html',pretty_print=True,doctype='<!DOCTYPE html>'))

# MÓDULO 3: producto y backlog aplicados al mismo caso de IA.
p=BASE/'entregables/MODULO 3/Contenido/contenido.html'; tree=html.parse(str(p)); a=tree.xpath('//article')[0]
opening(a,'''<p>El equipo ya conoce los marcos. Ahora debe responder la pregunta que evita construir funciones inútiles: <strong>¿qué problema vale la pena resolver primero?</strong></p><p>Seguiremos dos casos. TurnoYa conserva ejemplos de producto digital; el <strong>asistente universitario con IA</strong> permite distinguir una métrica técnica de un beneficio real para estudiantes.</p><h3>Cómo recorrer este módulo</h3><ol><li>Convertir una necesidad en visión y objetivos observables.</li><li>Representar opciones en un backlog sin confundirlas con órdenes.</li><li>Precisar trabajo con historias, criterios y calidad.</li><li>Priorizar y diseñar un MVP para aprender.</li><li>Comunicar evolución, lanzamientos, alcance y cambios.</li></ol>''')
append(a,1,'''<h3>1.2 Objetivos para un producto de IA</h3><p>“Mejorar la precisión del modelo” describe un resultado técnico incompleto. El producto existe para ayudar a alguien. En el asistente universitario podemos combinar tres niveles:</p><ul><li><strong>Beneficio:</strong> estudiantes resuelven consultas sin recibir información desactualizada.</li><li><strong>Comportamiento:</strong> proporción de consultas que se resuelve sin derivación innecesaria.</li><li><strong>Calidad técnica:</strong> respuestas correctas y respaldadas en una muestra definida.</li></ul><p>Las métricas se complementan. Un sistema puede obtener buen puntaje en una prueba y aun así resultar confuso, lento o poco utilizado.</p>''')
replace(a,5,'''<p>Una <strong>historia de usuario</strong> representa una necesidad con valor para alguien. Su formato frecuente es “Como [persona], quiero [capacidad], para [beneficio]”. Scrum no lo exige y no todo trabajo necesita disfrazarse de historia.</p>
<div class="analogia"><p><strong>Analogía del titular.</strong> Una historia es el titular que abre una conversación, no el artículo completo. Los criterios, ejemplos y decisiones aparecen al conversar.</p></div>
<h3>5.1 Del pedido a la necesidad</h3><table><caption>Reformular soluciones anticipadas</caption><thead><tr><th>Pedido</th><th>Necesidad que conviene explorar</th></tr></thead><tbody><tr><td>“Agregar un botón verde”.</td><td>Reconocer rápidamente si el turno fue confirmado.</td></tr><tr><td>“Usar un modelo más grande”.</td><td>Responder correctamente consultas ambiguas que hoy se derivan.</td></tr></tbody></table>
<p>Una historia posible es: “Como estudiante que inicia una inscripción, quiero conocer los documentos requeridos y su fuente, para evitar completar el trámite con información vencida”. Todavía debemos conversar sobre excepciones, accesibilidad y evidencia.</p>
<h3>5.2 INVEST como preguntas, no como examen</h3><ul><li><strong>Independiente:</strong> ¿podemos cambiar su orden sin desarmar todo el plan?</li><li><strong>Negociable:</strong> ¿deja espacio para descubrir la mejor solución?</li><li><strong>Valiosa:</strong> ¿explica el beneficio o el riesgo que reduce?</li><li><strong>Estimable:</strong> ¿sabemos lo suficiente para comparar su tamaño?</li><li><strong>Pequeña:</strong> ¿permite obtener evidencia en un horizonte breve?</li><li><strong>Testeable:</strong> ¿podemos reconocer un resultado aceptable?</li></ul>
<p>Una investigación técnica o la preparación de datos puede registrarse como elemento propio del backlog. No hace falta inventar “como sistema quiero…”. Sí hace falta explicitar para qué sirve y qué decisión habilitará.</p>
<h3>5.3 Dividir sin perder valor</h3><p>Conviene dividir por flujo, regla, tipo de usuario o escenario. Separar “hacer backend” y “hacer frontend” puede dejar dos piezas que nadie puede utilizar. Para el asistente, comenzar con consultas de inscripción y luego becas produce capacidades evaluables; dividir únicamente por componente técnico no.</p>''')
replace(a,8,'''<p>La <strong>Definition of Ready</strong> es una práctica opcional para conversar sobre si entendemos lo suficiente como para seleccionar trabajo. No forma parte obligatoria de Scrum.</p><p>Puede incluir criterios claros, dependencias visibles y ejemplos disponibles. Se vuelve dañina cuando funciona como una aduana: “el Product Owner entrega requisitos completos y el equipo recién entonces colabora”. La incertidumbre razonable no desaparece antes de empezar.</p><div class="criterio-profesional"><p><strong>Criterio profesional.</strong> Usá la preparación para revelar dudas evitables, no para exigir certeza falsa.</p></div>''')
append(a,11,'''<h3>11.2 MVP del asistente universitario</h3><p>La hipótesis no es “podemos conectar un modelo”, sino “los estudiantes resuelven consultas de inscripción con información correcta y comprensible”. Un MVP podría limitarse a un trámite, documentos aprobados, una interfaz simple y derivación a una persona cuando falta evidencia.</p><p>Antes de automatizar todo, una prueba tipo concierge puede permitir que una persona prepare las respuestas detrás de una interfaz y observar qué preguntan los estudiantes. Debe comunicarse la condición del piloto y protegerse la información. La decisión posterior puede ser ampliar, modificar o detener la inversión.</p>''')
append(a,15,'''<h3>15.2 Cuando cambia una fuente de datos</h3><p>Si la universidad modifica el reglamento de inscripción, el cambio no es una “tarea técnica inesperada”: puede invalidar respuestas. El equipo identifica qué fuentes y evaluaciones se ven afectadas, actualiza el backlog, informa el riesgo y vuelve a comprobar el comportamiento. La trazabilidad entre necesidad, dato y prueba permite reaccionar sin adivinar.</p>''')
a.set('data-revision-ia','2026-09-16'); p.write_bytes(etree.tostring(tree,encoding='utf-8',method='html',pretty_print=True,doctype='<!DOCTYPE html>'))

# MÓDULO 4: métricas + recorrido visual Trello/Jira/Notion.
p=BASE/'entregables/MODULO 4/Contenido/contenido.html'; tree=html.parse(str(p)); a=tree.xpath('//article')[0]
opening(a,'''<p>Tenemos un backlog ordenado. Ahora necesitamos responder sin fingir certeza: <strong>¿qué podemos hacer, cómo sabremos si avanzamos y cuándo debemos intervenir?</strong></p><p>El asistente universitario seguirá el recorrido desde una estimación hasta un tablero y sus métricas. Después veremos Trello, Jira y Notion como herramientas para sostener acuerdos que primero deben comprenderse.</p><h3>Cómo recorrer este módulo</h3><ol><li>Distinguir tamaño, tiempo, capacidad y pronóstico.</li><li>Planificar un Sprint con propósito.</li><li>Leer un tablero y gestionar bloqueos.</li><li>Interpretar métricas sin convertirlas en metas.</li><li>Elegir una herramienta y usar IA con revisión humana.</li></ol>''')
repl_text(a,'Un equipo comprometió 40 Story Points','''<p>Veamos un ejemplo numérico. Un equipo <strong>pronosticó</strong> 40 Story Points para un Sprint de diez días hábiles. La línea de referencia desciende 4 puntos por día. Esa diagonal ayuda a comparar, pero no describe cómo debe trabajar el equipo ni convierte los puntos en horas.</p>''')
append(a,16,'''<h3>16.2 Riesgos específicos de un sistema con IA</h3><p>Además de plazo y dependencias, el asistente puede sufrir cambios en las fuentes, respuestas plausibles pero incorrectas, costos variables o degradación al cambiar las consultas. El equipo registra cada riesgo con señal temprana, respuesta y responsable.</p><table><caption>Ejemplos de riesgo y respuesta</caption><thead><tr><th>Riesgo</th><th>Señal</th><th>Respuesta posible</th></tr></thead><tbody><tr><td>Documento desactualizado</td><td>La fecha de vigencia cambia.</td><td>Versionar fuentes y volver a ejecutar evaluaciones.</td></tr><tr><td>Respuestas sin respaldo</td><td>No se puede mostrar una fuente aprobada.</td><td>Derivar la consulta y registrar el caso.</td></tr><tr><td>Costo imprevisible</td><td>Sube el consumo por consulta.</td><td>Medir, fijar alertas y comparar alternativas.</td></tr></tbody></table>''')
replace(a,17,'''<p>Una herramienta conserva estados, conversaciones y datos. No decide por el equipo qué significa “Terminado”, qué trabajo aceptar ni qué métrica usar. El recorrido recomendado es <strong>Trello → Jira → Notion opcional</strong>: comenzar simple, agregar capacidad cuando exista una necesidad y documentar decisiones cuando corresponda.</p>
<h3>17.1 Trello: comprender el tablero</h3><p>Trello organiza trabajo en <strong>tableros, listas y tarjetas</strong>. Para el asistente, las listas podrían ser “Opciones”, “Preparado”, “En construcción”, “En validación” y “Terminado”. Una tarjeta representa una unidad de trabajo; puede contener responsable, fecha, checklist, etiquetas y conversación.</p>
<figure><img src="assets/trello-guia-tablero-2026.png" alt="Ejemplo oficial de un tablero de Trello con listas y tarjetas"><figcaption>Figura 17.1. Ejemplo de interfaz publicado en la guía oficial Trello 101, consultada el 15 de septiembre de 2026. Las tarjetas son de demostración del proveedor.</figcaption></figure>
<p><strong>Cómo leerla:</strong> primero mirá dónde se acumulan tarjetas; después, cuáles llevan demasiado tiempo o están bloqueadas. Los colores pueden clasificar tipo de trabajo, pero necesitan texto o una leyenda. El tablero no implementa Kanban por sí solo: faltan políticas y límites WIP acordados.</p>
<table><caption>Tarjeta didáctica del asistente</caption><thead><tr><th>Campo</th><th>Ejemplo</th></tr></thead><tbody><tr><td>Título</td><td>Mostrar la fuente de una respuesta de inscripción</td></tr><tr><td>Resultado esperado</td><td>El estudiante abre el documento y ve su vigencia.</td></tr><tr><td>Criterio clave</td><td>Si no hay fuente aprobada, la respuesta deriva la consulta.</td></tr><tr><td>Evidencia</td><td>Pruebas con casos correctos, vencidos y sin fuente.</td></tr></tbody></table>
<h3>17.2 Jira: backlog, flujo y reportes</h3><p>Jira agrega estructura para gestionar <strong>espacios, tipos de trabajo, backlog, Sprints, flujos y reportes</strong>, según la configuración y el plan. Historias, tareas y errores son tipos de elementos estándar; las subtareas pertenecen a un nivel inferior. No existe una jerarquía universal que debamos copiar sin necesidad.</p>
<figure><img src="assets/jira-configurar-columnas-2026.png" alt="Menú oficial de Jira con la opción para configurar columnas"><figcaption>Figura 17.2. Opción “Configure columns” en la guía oficial de inicio de Jira, consultada el 15 de septiembre de 2026. La interfaz puede cambiar.</figcaption></figure>
<p><strong>Cómo usarlo con criterio:</strong> configurá columnas que representen cambios reales de estado; cargá un elemento con propósito, criterios y vínculos; movelo cuando el estado cambie; y recién entonces interpretá burndown, velocity o control de flujo. Un reporte basado en tarjetas desactualizadas produce precisión aparente.</p>
<p>Para el asistente, una épica puede agrupar “Consultas de inscripción”; un elemento estándar puede ser “Citar la fuente vigente” y sus subtareas, si ayudan, separar integración y pruebas. Un error detectado en validación se registra como bug porque describe el tipo de trabajo, no porque sea un nivel inferior a toda tarea.</p>
<h3>17.3 Notion como complemento opcional</h3><p>Notion permite relacionar proyectos, tareas, documentos y decisiones en bases con vistas de tabla, tablero o cronograma. Puede servir para conservar una ficha del experimento, sus supuestos, resultados y decisión posterior. No reemplaza Jira o Trello por obligación, ni es un contenido mínimo de la materia.</p>
<p>Una página del asistente podría reunir: pregunta investigada, conjunto de evaluación, versión de las fuentes, resultado, riesgos y enlace al elemento del tablero. Si el equipo duplica el estado en dos plataformas, debe definir cuál es la fuente de verdad.</p>
<h3>17.4 IA y agentes dentro de la gestión</h3><p>Las funciones cambian según producto y plan. En la documentación oficial consultada, Jira puede ayudar a redactar o dividir elementos y permite asignar trabajo a agentes; Notion Agent puede actuar sobre páginas y bases según permisos. Son capacidades de apoyo, no nuevas responsabilidades de Scrum.</p>
<ol><li>Una persona formula el objetivo y aporta contexto autorizado.</li><li>La IA propone un resumen, una división o una acción.</li><li>La persona revisa exactitud, permisos, datos y efectos.</li><li>La herramienta registra el resultado y alguien conserva la responsabilidad.</li></ol>
<div class="criterio-profesional"><p><strong>Criterio profesional.</strong> Automatizá una tarea cuando sus límites, permisos y revisión estén claros. No delegues a un agente una decisión de prioridad o aceptación cuya responsabilidad sigue siendo humana.</p></div>
<h3>17.5 Elegir sin perseguir novedades</h3><table><caption>Elección orientada por necesidad</caption><thead><tr><th>Necesidad dominante</th><th>Opción razonable</th></tr></thead><tbody><tr><td>Aprender flujo con poca configuración</td><td>Trello o tablero físico.</td></tr><tr><td>Backlog, Sprints, tipos de trabajo y reportes integrados</td><td>Jira, si el equipo sostendrá la configuración.</td></tr><tr><td>Documentar decisiones y relacionarlas con tareas</td><td>Notion como complemento.</td></tr></tbody></table>
<p>También existen Azure DevOps, Asana, Monday.com y otras alternativas. La marca importa menos que la calidad de los acuerdos, la actualización de los datos y el costo de administración.</p>''',figures=False)
a.set('data-revision-ia','2026-09-16'); p.write_bytes(etree.tostring(tree,encoding='utf-8',method='html',pretty_print=True,doctype='<!DOCTYPE html>'))

# MÓDULO 5: equipos de IA, mejora y casos con evidencia.
p=BASE/'entregables/MODULO 5/Contenido/contenido.html'; tree=html.parse(str(p)); a=tree.xpath('//article')[0]
opening(a,'''<p>Un buen backlog y un tablero actualizado no resuelven por sí solos una discusión entre especialistas, una aprobación tardía o una respuesta incorrecta en producción. Este módulo pregunta <strong>cómo sostener el aprendizaje entre personas y dentro de la organización</strong>.</p><p>El asistente universitario reúne producto, dominio, datos, software, experiencia de usuario, evaluación y operaciones. Veremos cómo esas capacidades colaboran, cómo aprenden de incidentes y cómo deciden con evidencia.</p><h3>Cómo recorrer este módulo</h3><ol><li>Componer un equipo capaz de terminar trabajo útil.</li><li>Distribuir decisiones y sostener conversaciones seguras.</li><li>Convertir feedback y retrospectivas en mejoras comprobables.</li><li>Integrar calidad, entrega y operación.</li><li>Analizar casos reales y escenarios didácticos sin confundirlos.</li></ol>''')
replace(a,1,'''<p>Un <strong>equipo multidisciplinario</strong> reúne colectivamente las habilidades necesarias para crear un resultado utilizable. No significa que todas las personas sepan hacer todo ni que nunca exista una dependencia externa.</p>
<h3>1.1 El equipo del asistente universitario</h3><table><caption>Capacidades que deben coordinarse</caption><thead><tr><th>Capacidad</th><th>Pregunta que aporta</th></tr></thead><tbody><tr><td>Producto y dominio universitario</td><td>¿Qué consulta importa y qué fuente está vigente?</td></tr><tr><td>Datos e IA</td><td>¿Qué información utiliza el sistema y cómo se evalúa?</td></tr><tr><td>Software y operaciones</td><td>¿Cómo se integra, protege, observa y mantiene?</td></tr><tr><td>Experiencia de usuario</td><td>¿El estudiante comprende la respuesta y puede actuar?</td></tr><tr><td>Calidad y riesgo</td><td>¿Qué puede fallar y qué evidencia exige el contexto?</td></tr></tbody></table>
<p>Las capacidades pueden residir en distintas personas. La meta es reducir transferencias y esperas, compartir conocimiento y hacer visibles las dependencias que no puedan eliminarse.</p>
<h3>1.2 Tamaño y estabilidad</h3><p>La Guía Scrum describe un Scrum Team típicamente de diez personas o menos. Es una orientación, no una fórmula para todo equipo. El tamaño debe permitir comunicación y, al mismo tiempo, reunir las habilidades necesarias.</p><p>La estabilidad favorece confianza y conocimiento compartido. Mantener a una persona imprescindible para cada componente, sin reemplazo ni documentación, produce fragilidad aunque el organigrama sea estable.</p>
<h3>1.3 Resultado compartido</h3><ul><li>El equipo se organiza alrededor de un objetivo, no de la ocupación individual.</li><li>Las especialidades colaboran desde el inicio, en lugar de pasarse trabajo al final.</li><li>La calidad y la operación forman parte del resultado.</li><li>Los acuerdos se revisan con evidencia.</li></ul>''')
append(a,7,'''<h3>7.4 Feedback sobre resultados de IA</h3><p>“El modelo alucina” es demasiado general para actuar. Un reporte útil conserva la consulta, la respuesta, la fuente esperada, el contexto y el impacto. El equipo evita incluir datos personales innecesarios y distingue un defecto reproducible de una percepción aislada.</p>''')
append(a,13,'''<h3>13.4 La deuda oculta de los sistemas de IA</h3><p>Un modelo es solo una parte del producto. Datos, configuraciones, dependencias y consumidores pueden acumular deuda difícil de ver. La investigación sobre deuda técnica en sistemas de aprendizaje automático documenta riesgos como dependencias de datos y bucles de retroalimentación.</p><p>Para el asistente, la DoD puede exigir versionar las fuentes, registrar el conjunto de evaluación, controlar permisos y preparar observabilidad. Mejorar el modelo sin mantener ese sistema puede aumentar complejidad sin mejorar el servicio.</p>''')
replace(a,18,'''<p>Los casos permiten contrastar fundamentos, prácticas y resultados. Para leerlos, separá <strong>contexto, intervención, evidencia y límites</strong>. Una fuente institucional describe una perspectiva; un escenario didáctico practica razonamiento y no aporta estadísticas reales.</p>
<h3>18.1 Caso real: Sentinel y el FBI</h3><p>En 2010, el FBI informó problemas de desempeño y costos en Sentinel y explicó que usaría desarrollo ágil para completar funciones pendientes, revisar requisitos y ordenar prioridades. En 2012 anunció el despliegue del sistema para todos sus empleados y la continuidad de mejoras a partir de comentarios.</p><p>Podemos observar un despliegue y un cambio de enfoque. Las fuentes no permiten atribuir el resultado exclusivamente a Scrum ni concluir que la agilidad garantiza ahorro. El caso sirve para discutir entrega utilizable, priorización y aprendizaje bajo supervisión formal.</p>
<h3>18.2 Caso real: colaboración de liderazgo en ING</h3><p>Un informe de experiencia de Agile Alliance relata el trabajo de un Agile Coach con Product Owners y Chapter Leads de cuatro squads de ING entre 2015 y 2017. El equipo de liderazgo hizo visibles tensiones entre entrega de corto plazo y capacidades técnicas de largo plazo.</p><p>Es un testimonio situado. “Squad”, “Chapter Lead” y “Agile Coach” describen esa organización; no son responsabilidades obligatorias de Scrum. La lección transferible es conversar explícitamente sobre objetivos legítimos que compiten por el mismo tiempo.</p>
<h3>18.3 Caso documentado de ingeniería de IA: deuda técnica</h3><p>El trabajo de Google Research <em>Hidden Technical Debt in Machine Learning Systems</em> analiza cómo un sistema de aprendizaje automático puede acumular deuda en dependencias de datos, configuración, consumidores y bucles de retroalimentación. No es un caso de adopción de Scrum ni prueba una metodología.</p><p>Su aporte para la gestión es directo: el backlog y la Definition of Done no deben mirar solo el modelo. El equipo necesita hacer visible el sistema que permite entrenar, evaluar, desplegar y observar. Una mejora local de una métrica puede crear costo o riesgo en otra parte.</p>
<h3>18.4 Escenario didáctico: soporte con flujo impredecible</h3><p>Un equipo recibe incidentes y pedidos de tamaño variable. Sus Sprints se interrumpen constantemente. Decide visualizar el flujo, definir una política explícita para incidentes críticos, limitar WIP y medir Cycle Time por clase de servicio.</p><p>El resultado no se inventa de antemano: durante varias semanas compara tiempos, calidad y demanda. Si mejora la previsibilidad, conserva la política; si aparecen nuevas esperas, la adapta. El aprendizaje es elegir por naturaleza del trabajo y comprobar el efecto.</p>
<h3>18.5 Escenario didáctico: adopción superficial</h3><p>Otra organización renombra al jefe de proyecto como Scrum Master, usa el Daily para reportes y mantiene decisiones centralizadas. Las retrospectivas repiten problemas sin producir acciones. Aunque existen Sprints y tableros, las responsabilidades y los ciclos de aprendizaje no cambiaron.</p><p>El diagnóstico no es “las personas se resisten”: hay incoherencia entre lenguaje, autoridad e incentivos. Una intervención razonable comienza por explicitar decisiones, elegir un piloto, formar capacidades y medir resultados que importan.</p>
<h3>18.6 Desafíos frecuentes</h3><table><caption>Desafío, señal e intervención inicial</caption><thead><tr><th>Desafío</th><th>Señal</th><th>Intervención</th></tr></thead><tbody><tr><td>Adopción superficial</td><td>Rituales sin adaptación.</td><td>Volver al propósito y medir decisiones/resultados.</td></tr><tr><td>Métricas como castigo</td><td>Se comparan puntos entre personas o equipos.</td><td>Definir qué decisión apoya cada indicador.</td></tr><tr><td>Autonomía aparente</td><td>El equipo espera autorización para cada detalle.</td><td>Explicitar límites y trasladar decisiones.</td></tr><tr><td>Escalado prematuro</td><td>Se agregan roles antes de comprender dependencias.</td><td>Aprender con un alcance acotado y eliminar dependencias.</td></tr><tr><td>IA sin gobierno</td><td>No se sabe qué datos, versión o evaluación produjo el resultado.</td><td>Registrar trazabilidad, permisos y revisión humana.</td></tr></tbody></table>''',figures=False)
replace(a,19,'''<p>La universidad quiere reducir consultas repetitivas sin entregar información incorrecta. Financia un piloto del asistente para inscripciones y decidirá su continuidad con evidencia.</p>
<ol><li><strong>Delimitar.</strong> Sponsor, usuarios y especialistas acuerdan objetivo, fuentes autorizadas, restricciones, riesgos y criterio de cierre.</li><li><strong>Elegir el enfoque.</strong> El equipo usa Scrum para aprender mediante incrementos y un flujo Kanban para incidentes del piloto. Explica qué problema resuelve cada práctica.</li><li><strong>Orientar producto.</strong> El Product Goal busca una experiencia confiable; el backlog reúne necesidades, calidad, datos, investigaciones y operación.</li><li><strong>Preparar evidencia.</strong> Historias y criterios describen el comportamiento. Un conjunto de consultas conocidas examina exactitud y respaldo; pruebas con estudiantes examinan comprensión.</li><li><strong>Planificar.</strong> El equipo considera capacidad, incertidumbre y dependencias. Formula un Sprint Goal; los puntos apoyan la conversación y no se convierten en horas.</li><li><strong>Construir y seguir.</strong> El tablero muestra estado, bloqueos y WIP. La DoD incluye código, fuentes versionadas, evaluación, seguridad y observabilidad acordadas.</li><li><strong>Inspeccionar.</strong> La Review contrasta el incremento con interesados; la Retrospectiva cambia el sistema de trabajo. Errores se registran con contexto y se priorizan por impacto.</li><li><strong>Operar con responsabilidad.</strong> Cuando falta evidencia, el asistente deriva la consulta. Alertas de costo, calidad y vigencia activan respuestas acordadas.</li><li><strong>Cerrar y decidir.</strong> Se comparan resultados con la línea de base, se transfieren responsabilidades y el sponsor decide ampliar, modificar o detener el producto.</li></ol>
<div class="criterio-profesional"><p><strong>Lectura profesional.</strong> La coherencia no está en usar muchas prácticas, sino en conectar propósito, personas, trabajo, evidencia y decisión.</p></div>''')
a.set('data-revision-ia','2026-09-16'); p.write_bytes(etree.tostring(tree,encoding='utf-8',method='html',pretty_print=True,doctype='<!DOCTYPE html>'))

# Incorporar referencias oficiales de interfaz verificadas visualmente.
assets=BASE/'entregables/MODULO 4/Contenido/assets'; assets.mkdir(exist_ok=True)
sources={
 Path(r'C:/Users/Pablo/AppData/Local/Temp/browser-use/assets/e06ae6b3-7e6f-4f94-8a2d-41bf870cd027/8cd47dcf2984125a.jpg'): assets/'trello-guia-tablero-2026.png',
 Path(r'C:/Users/Pablo/AppData/Local/Temp/browser-use/assets/3e92b38a-85b5-4fba-b738-9b0b06a7684e/d3b5c190778f86b8.webp'): assets/'jira-configurar-columnas-2026.png'}
for src,dst in sources.items():
    with Image.open(src) as im: im.convert('RGB').save(dst,'PNG',optimize=True)

# Auditoría básica antes de exportar.
report=[]
for n in range(2,6):
    q=BASE/'entregables'/f'MODULO {n}'/'Contenido/contenido.html'; t=html.parse(str(q)); ar=t.xpath('//article')[0]
    report.append({'modulo':n,'palabras':len(ar.text_content().split()),'h2':len(ar.xpath('./h2')),'h3':len(ar.xpath('./h3')),'tablas':len(ar.xpath('.//table')),'figuras':len(ar.xpath('.//figure')),'marcador':ar.get('data-revision-ia')})
(BASE/'.qa/revision-pedagogica-ia/revision-modulos2-5.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps(report,ensure_ascii=False,indent=2))
